# Fail2Ban configuration file
#
# Regexp to catch known spambots and software alike. Please verify
# that it is your intent to block IPs which were driven by
# above mentioned bots.


[Definition]

# To test, you can inject this example into log
# echo `date +'%Y-%m-%d %H:%M:%S'`" WARNING 1.2.3.4         recaptcha: Account creation blocked for 1.2.3.4" >> /home/dolibarr/asso.dolibarr.org/dolibarr_documents/dolibarr_website_marketplace.log
# echo `date +'%Y-%m-%d %H:%M:%S'`" WARNING 1.2.3.4         1234567     33 recaptcha: Account creation blocked for 1.2.3.4" >> /home/dolibarr/asso.dolibarr.org/dolibarr_documents/dolibarr_website_marketplace.log
#
# then 
# fail2ban-client status web-marketplace-rulesregister 
#
# To test rule file on a existing log file
# fail2ban-regex /home/dolibarr/asso.dolibarr.org/dolibarr_documents/dolibarr_website_marketplace.log /etc/fail2ban/filter.d/web-dolibarr-rulesregister.conf --print-all-matched

failregex = ^ [A-Z\s]+ <HOST>\s.*Account creation blocked for
ignoreregex =
