
[web-marketplace-captcha]

; rule against call to /login-register.php (see file etc/fail2ban/filter.d/web-marketplace-captcha)
enabled = true
port    = http,https
filter  = web-marketplace-captcha
logpath = /home/dolibarr/asso.dolibarr.org/dolibarr_documents/dolibarr_website_marketplace.log
action  = %(action_mw)s
bantime  = 4320000   ; 50 days
findtime = 86400     ; 1 day
maxretry = 10

